FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy codebase and build Next.js application
COPY . .
RUN npm run build

# Expose Next.js port
EXPOSE 3000

# Start command
CMD ["npm", "run", "start"]
