services:
  - type: web
    name: zinou-tv-api
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php backend/artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: ZINOU TV
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: X_API_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
